### ISSUE TITLE
LCDproc is now officially on github

### ISSUE THREAD

**Issue by dglaude** [MalteP/lcdproc-drivers#1]
Dear MatleP

[You may want to know that LCDproc is now on github](https://github.com/lcdproc/lcdproc).

This repository seems to contain patch to add diver for fwa3210/fws7600.
I don't know what those LCDs are and if they are common.
Maybe you want to fork the main LCDproc repository and add your driver to your copy.

Then try a Pull-request, no guarantee it will be accepted, but it might make things more easy and also help tracking contribution origin.

Regards

**Comment by MalteP** [comment]
Hi,

those are network appliances which are already EOL / discontinued by the manufacturer.
I developed the driver at work back in 2011, just uploaded my patch to Github in case somebody is still running this hardware. Just have a look at the LCDproc mailing list: http://comments.gmane.org/gmane.comp.sysutils.lcdproc/13551

Don't think that it will be accepted and i also can't test with newer versions of LCDproc because i don't know if there are still some of those machines at my workplace.

Best regards,
Malte
